---
version: '3'
services:
  testbed_icmp:
    build:
      context: .
      dockerfile: ./docker/testbed/icmp/Dockerfile
    networks:
      - default
  testbed_web:
    build:
      context: .
      dockerfile: ./docker/testbed/web/Dockerfile
    networks:
      - default
    # ports:
    #   - 80:80
    #   - 443:443
  testbed_ssh:
    build:
      context: .
      dockerfile: ./docker/testbed/ssh/Dockerfile
    networks:
      - default
    # ports:
    #   - 22:22
  testbed_mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_DATABASE=randomdb
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=CHANGEME
    networks:
      - default
    # ports:
    #   - 3306:3306
  testbed_mssql:
    image: microsoft/mssql-server-linux:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    networks:
      - default
    # ports:
    #   - 1433:1433
  testbed_ftp:
    build:
      context: .
      dockerfile: ./docker/testbed/ftp/Dockerfile
    networks:
      - default
    # ports:
    #   - 21:21
  testbed_elasticsearch:
    build:
      context: .
      dockerfile: ./docker/testbed/elasticsearch/Dockerfile
    networks:
      - default
    # ports:
    #   - 9200:9200
  testbed_smb:
    build:
      context: .
      dockerfile: ./docker/testbed/smb/Dockerfile
    networks:
      - default
    # ports:
      # - 139:139
      # - 445:445
  testbed_dns:
    build:
      context: .
      dockerfile: ./docker/testbed/dns/Dockerfile
    networks:
      - default
    # ports:
      # - 53:53/udp
      # - 53:53
  testbed_postgresql:
    build:
      context: .
      dockerfile: ./docker/testbed/postgresql/Dockerfile
    networks:
      - default
    # ports:
    #   - 5432:5432
  testbed_smtp:
    build:
      context: .
      dockerfile: ./docker/testbed/smtp/Dockerfile
    networks:
      - default
    # ports:
    #   - 25:25
    #   - 578:587

networks:
  default:
